spring:
  application:
    name: disaster-code
  #数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: ymc
#    password: uvr14758
#    url: jdbc:mysql://119.3.255.115:4337/disaster_code
    hikari:
      #此属性控制池中链接的最长生命周期，值 0 表示无限生命周期 默认30分钟
      max-lifetime: 1800000
      #连接超时时间，默认 30000（30秒）
      connection-timeout: 30000
      #连接池最大链接数，默认是 10
      maximum-pool-size: 20
      #空闲链接存活最大时间，默认 600000（10分钟）
      idle-timeout: 30000
      #链接将被测试活动的最大时间
      validation-timeout: 6000
      #连接到数据库时等待的等待时间
      login-timeout: 5
      #池中维护的最小空闲链接数
      minimum-idle: 5

    username: s2485523800
    password: S1z2x3c4v5b
    url: jdbc:mysql://s2485523800.mysql.polardb.rds.aliyuncs.com/disaster_code

  mvc:
    #声明路径规则
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 6002

mybatis-plus:
  configuration:
    #不转下划线，就直接驼峰
    map-underscore-to-camel-case: false
    #log实现类
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #不转下划线
      table-underline: false
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

oss:
  endPoint: https://oss-cn-beijing.aliyuncs.com
  accessKeyId:
  accessKeySecret:
  bucketName:
  filePrefix: